### ISSUE TITLE
Error under update-help

### ISSUE THREAD

**Issue by it-praktyk** [9to5IT/PSLogging#3]
**Issue**
PS \> update-help
update-help : Failed to update Help for the module(s) 'PSLogging' with UI culture(s) {en-US} : Unable to retrieve the
HelpInfo XML file for UI culture en-US. Make sure the HelpInfoUri property in the module manifest is valid or check
your network connection and then try the command again.
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Workaround**
Remove value for HelpInfoURI in the file PSLogging.psd1

**Resolution**
Transform comment based help to xml-based (?)

**Comment by 9to5IT** [comment]
Hi it-praktyk,

Thanks very much for the info and sorry about the delay... I have been away on holidays and hence haven't been able to do much until now.

To solve this, I have commented out the HelpInfoURI in the psd1 file, so this should fix your issue.

Out of curiosity, what version of PowerShell are you running?

Thanks
Luca

**Comment by it-praktyk** [comment]
Hi,
I use the PSLogging module on Windows 8.1 with Windows Management Framework 5.0 Production Preview - KB3066437 

PS C:\> $psversiontable | fl

Name  : PSVersion
Value : 5.0.10514.6

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.34209

Name  : BuildVersion
Value : 10.0.10514.6

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : PSRemotingProtocolVersion
Value : 2.3

**Comment by 9to5IT** [comment]
Thanks for the info. 

I have updated the manifest file, so that should resolve the issue now. 

Thanks for letting me know if the issue. 

Regards,
Luca

On 22 Nov 2015, at 23:57, Wojciech Sciesinski <notifications@github.com> wrote:

Hi,
I use the PSLogging module on Windows 8.1 with Windows Management Framework 5.0 Production Preview - KB3066437

PS C:> $psversiontable | fl

Name : PSVersion
Value : 5.0.10514.6

Name : WSManStackVersion
Value : 3.0

Name : SerializationVersion
Value : 1.1.0.1

Name : CLRVersion
Value : 4.0.30319.34209

Name : BuildVersion
Value : 10.0.10514.6

Name : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name : PSRemotingProtocolVersion
Value : 2.3
